In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [15]:
import pandas as pd
import sqlite3

# CSV File
df1 = pd.read_csv('/content/credit_risk_dataset_1000.csv')

# JSON File
df2 = pd.read_json('/content/credit_risk_dataset_1000.json')

# Create SQLite Database from CSV
conn = sqlite3.connect('/content/credit_risk.db')

df1.to_sql(
    'loan_history',
    conn,
    if_exists='replace',
    index=False
)

# Read Database Table
df3 = pd.read_sql(
    'SELECT * FROM loan_history',
    conn
)

conn.close()

In [13]:
df1.head()

,customer_id,age,gender,region,education_level,employment_type,annual_income,loan_amount,loan_purpose,credit_score,repayment_history,transaction_count,spending_ratio,join_date,default_flag
0,10001,59,Female,South,Primary,Self-Employed,1538977,1436826,Car,385,0,86,15.82,2019-06-06,1
1,10002,49,Male,West,Primary,Salaried,386371,1409385,Education,766,1,297,25.77,2021-11-01,0
2,10003,35,Female,East,Primary,Self-Employed,796275,1441730,Education,352,0,56,36.57,2023-12-22,1
3,10004,63,Female,North,Primary,Salaried,1874502,274737,Car,534,9,119,73.20,2018-09-05,0
4,10005,28,Male,North,Primary,Salaried,274591,944235,Car,732,9,209,57.42,2021-09-03,0

In [14]:
df2.head()

,customer_id,age,gender,region,education_level,employment_type,annual_income,loan_amount,loan_purpose,credit_score,repayment_history,transaction_count,spending_ratio,join_date,default_flag
0,10001,59,Female,South,Primary,Self-Employed,1538977,1436826,Car,385,0,86,15.82,2019-06-06,1
1,10002,49,Male,West,Primary,Salaried,386371,1409385,Education,766,1,297,25.77,2021-11-01,0
2,10003,35,Female,East,Primary,Self-Employed,796275,1441730,Education,352,0,56,36.57,2023-12-22,1
3,10004,63,Female,North,Primary,Salaried,1874502,274737,Car,534,9,119,73.20,2018-09-05,0
4,10005,28,Male,North,Primary,Salaried,274591,944235,Car,732,9,209,57.42,2021-09-03,0

In [16]:
df3.head()

,customer_id,age,gender,region,education_level,employment_type,annual_income,loan_amount,loan_purpose,credit_score,repayment_history,transaction_count,spending_ratio,join_date,default_flag
0,10001,59,Female,South,Primary,Self-Employed,1538977,1436826,Car,385,0,86,15.82,2019-06-06,1
1,10002,49,Male,West,Primary,Salaried,386371,1409385,Education,766,1,297,25.77,2021-11-01,0
2,10003,35,Female,East,Primary,Self-Employed,796275,1441730,Education,352,0,56,36.57,2023-12-22,1
3,10004,63,Female,North,Primary,Salaried,1874502,274737,Car,534,9,119,73.20,2018-09-05,0
4,10005,28,Male,North,Primary,Salaried,274591,944235,Car,732,9,209,57.42,2021-09-03,0

In [18]:
api_data = {
    "inflation_rate": 5.4,
    "repo_rate": 6.5,
    "gdp_growth": 7.1
}

api_df = pd.DataFrame([api_data])

api_df

   inflation_rate  repo_rate  gdp_growth
0             5.4        6.5         7.1

In [19]:
merged_df = df1.merge(
    df2,
    on='customer_id',
    how='left',
    suffixes=('_csv', '_json')
)

merged_df = merged_df.merge(
    df3,
    on='customer_id',
    how='left'
)

print(merged_df.shape)
merged_df.head()

(1000, 43)

,customer_id,age_csv,gender_csv,region_csv,education_level_csv,employment_type_csv,annual_income_csv,loan_amount_csv,loan_purpose_csv,credit_score_csv,...,employment_type,annual_income,loan_amount,loan_purpose,credit_score,repayment_history,transaction_count,spending_ratio,join_date,default_flag
0,10001,59,Female,South,Primary,Self-Employed,1538977,1436826,Car,385,...,Self-Employed,1538977,1436826,Car,385,0,86,15.82,2019-06-06,1
1,10002,49,Male,West,Primary,Salaried,386371,1409385,Education,766,...,Salaried,386371,1409385,Education,766,1,297,25.77,2021-11-01,0
2,10003,35,Female,East,Primary,Self-Employed,796275,1441730,Education,352,...,Self-Employed,796275,1441730,Education,352,0,56,36.57,2023-12-22,1
3,10004,63,Female,North,Primary,Salaried,1874502,274737,Car,534,...,Salaried,1874502,274737,Car,534,9,119,73.20,2018-09-05,0
4,10005,28,Male,North,Primary,Salaried,274591,944235,Car,732,...,Salaried,274591,944235,Car,732,9,209,57.42,2021-09-03,0

In [20]:
merged_df.shape

(1000, 43)

In [21]:
merged_df.columns

Index(['customer_id', 'age_csv', 'gender_csv', 'region_csv',
       'education_level_csv', 'employment_type_csv', 'annual_income_csv',
       'loan_amount_csv', 'loan_purpose_csv', 'credit_score_csv',
       'repayment_history_csv', 'transaction_count_csv', 'spending_ratio_csv',
       'join_date_csv', 'default_flag_csv', 'age_json', 'gender_json',
       'region_json', 'education_level_json', 'employment_type_json',
       'annual_income_json', 'loan_amount_json', 'loan_purpose_json',
       'credit_score_json', 'repayment_history_json', 'transaction_count_json',
       'spending_ratio_json', 'join_date_json', 'default_flag_json', 'age',
       'gender', 'region', 'education_level', 'employment_type',
       'annual_income', 'loan_amount', 'loan_purpose', 'credit_score',
       'repayment_history', 'transaction_count', 'spending_ratio', 'join_date',
       'default_flag'],
      dtype='object')

In [22]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 43 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   customer_id             1000 non-null   int64
 1   age_csv                 1000 non-null   int64
 2   gender_csv              1000 non-null   object
 3   region_csv              1000 non-null   object
 4   education_level_csv     1000 non-null   object
 5   employment_type_csv     1000 non-null   object
 6   annual_income_csv       1000 non-null   int64
 7   loan_amount_csv         1000 non-null   int64
 8   loan_purpose_csv        1000 non-null   object
 9   credit_score_csv        1000 non-null   int64
 10  repayment_history_csv   1000 non-null   int64
 11  transaction_count_csv   1000 non-null   int64
 12  spending_ratio_csv      1000 non-null   float64
 13  join_date_csv           1000 non-null   object
 14  default_flag_csv        1000 non-null   int64
 15  age_json                1000 non-null   int64
 16  gender_json             1000 non-null   object
 17  region_json             1000 non-null   object
 18  education_level_json    1000 non-null   object
 19  employment_type_json    1000 non-null   object
 20  annual_income_json      1000 non-null   int64
 21  loan_amount_json        1000 non-null   int64
 22  loan_purpose_json       1000 non-null   object
 23  credit_score_json       1000 non-null   int64
 24  repayment_history_json  1000 non-null   int64
 25  transaction_count_json  1000 non-null   int64
 26  spending_ratio_json     1000 non-null   float64
 27  join_date_json          1000 non-null   object
 28  default_flag_json       1000 non-null   int64
 29  age                     1000 non-null   int64
 30  gender                  1000 non-null   object
 31  region                  1000 non-null   object
 32  education_level         1000 non-null   object
 33  employment_type         1000 non-null   object
 34  annual_income           1000 non-null   int64
 35  loan_amount             1000 non-null   int64
 36  loan_purpose            1000 non-null   object
 37  credit_score            1000 non-null   int64
 38  repayment_history       1000 non-null   int64
 39  transaction_count       1000 non-null   int64
 40  spending_ratio          1000 non-null   float64
 41  join_date               1000 non-null   object
 42  default_flag            1000 non-null   int64
dtypes: float64(3), int64(22), object(18)
memory usage: 336.1+ KB

In [23]:
merged_df.describe()

,customer_id,age_csv,annual_income_csv,loan_amount_csv,credit_score_csv,repayment_history_csv,transaction_count_csv,spending_ratio_csv,default_flag_csv,age_json,...,spending_ratio_json,default_flag_json,age,annual_income,loan_amount,credit_score,repayment_history,transaction_count,spending_ratio,default_flag
count,1000.000000,1000.000000,1.000000e+03,1.000000e+03,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,...,1000.000000,1000.000000,1000.000000,1.000000e+03,1.000000e+03,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,10500.500000,42.515000,1.333260e+06,7.812263e+05,572.429000,5.963000,258.502000,50.251730,0.278000,42.515000,...,50.251730,0.278000,42.515000,1.333260e+06,7.812263e+05,572.429000,5.963000,258.502000,50.251730,0.278000
std,288.819436,12.611059,6.759758e+05,4.218811e+05,155.447486,3.853372,140.683132,26.086427,0.448238,12.611059,...,26.086427,0.448238,12.611059,6.759758e+05,4.218811e+05,155.447486,3.853372,140.683132,26.086427,0.448238
min,10001.000000,21.000000,1.515390e+05,5.021500e+04,300.000000,0.000000,10.000000,5.120000,0.000000,21.000000,...,5.120000,0.000000,21.000000,1.515390e+05,5.021500e+04,300.000000,0.000000,10.000000,5.120000,0.000000
25%,10250.750000,32.000000,7.343785e+05,4.192425e+05,437.000000,3.000000,138.000000,28.337500,0.000000,32.000000,...,28.337500,0.000000,32.000000,7.343785e+05,4.192425e+05,437.000000,3.000000,138.000000,28.337500,0.000000
50%,10500.500000,43.000000,1.336916e+06,7.846125e+05,575.000000,6.000000,262.000000,50.875000,0.000000,43.000000,...,50.875000,0.000000,43.000000,1.336916e+06,7.846125e+05,575.000000,6.000000,262.000000,50.875000,0.000000
75%,10750.250000,53.000000,1.909942e+06,1.133346e+06,700.250000,9.000000,377.000000,73.302500,1.000000,53.000000,...,73.302500,1.000000,53.000000,1.909942e+06,1.133346e+06,700.250000,9.000000,377.000000,73.302500,1.000000
max,11000.000000,64.000000,2.498991e+06,1.496743e+06,850.000000,12.000000,499.000000,94.970000,1.000000,64.000000,...,94.970000,1.000000,64.000000,2.498991e+06,1.496743e+06,850.000000,12.000000,499.000000,94.970000,1.000000

In [25]:
pip install ydata-profiling

Collecting ydata-profiling
  Downloading ydata_profiling-4.18.4-py2.py3-none-any.whl.metadata (23 kB)
Requirement already satisfied: scipy<1.17,>=1.8 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (1.16.3)
Requirement already satisfied: pandas!=1.4.0,<3.0,>1.5 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (2.2.2)
Requirement already satisfied: matplotlib<=3.10,>=3.5 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (3.10.0)
Requirement already satisfied: pydantic<3,>=2 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (2.12.3)
Requirement already satisfied: PyYAML<6.1,>=6.0.3 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (6.0.3)
Requirement already satisfied: jinja2<3.2,>=3.1.6 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (3.1.6)
Collecting visions<0.8.2,>=0.7.5 (from visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling)
  Downloading visions-0.8.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy<2.4,>=1.22 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (2.0.2)
Collecting minify-html>=0.15.0 (from ydata-profiling)
  Downloading minify_html-0.18.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (18 kB)
Collecting filetype>=1.0.0 (from ydata-profiling)
  Downloading filetype-1.2.0-py2.py3-none-any.whl.metadata (6.5 kB)
Collecting phik<0.13,>=0.12.5 (from ydata-profiling)
  Downloading phik-0.12.5-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (5.6 kB)
Requirement already satisfied: requests<3,>=2.32.0 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (2.32.4)
Requirement already satisfied: tqdm<5,>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (4.67.3)
Requirement already satisfied: seaborn<0.14,>=0.10.1 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (0.13.2)
Collecting multimethod<2,>=1.4 (from ydata-profiling)
  Downloading multimethod-1.12-py3-none-any.whl.metadata (9.6 kB)
Requirement already satisfied: statsmodels<1,>=0.13.2 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (0.14.6)
Requirement already satisfied: typeguard<5,>=4 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (4.5.2)
Collecting imagehash==4.3.2 (from ydata-profiling)
  Downloading ImageHash-4.3.2-py2.py3-none-any.whl.metadata (8.4 kB)
Requirement already satisfied: wordcloud>=1.9.4 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (1.9.6)
Collecting dacite<2,>=1.9 (from ydata-profiling)
  Downloading dacite-1.9.2-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: numba<0.63,>=0.60 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (0.60.0)
Requirement already satisfied: PyWavelets in /usr/local/lib/python3.12/dist-packages (from imagehash==4.3.2->ydata-profiling) (1.9.0)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (from imagehash==4.3.2->ydata-profiling) (11.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2<3.2,>=3.1.6->ydata-profiling) (3.0.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (26.2)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (2.9.0.post0)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /usr/local/lib/python3.12/dist-packages (from numba<0.63,>=0.60->ydata-profiling) (0.43.0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas!=1.4.0,<3.0,>1.5->ydata-profiling) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas!=1.4.0,<3.0,>1.5->ydata-profiling) (2026.2)
Requirement already satisfied: joblib>=0.14.1 in /usr/local/lib/python3.12/dist-packages (from phik<0.13,>=0.12.5->ydata-profiling) (1.5.3)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2->ydata-profiling) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2->ydata-profiling) (2.41.4)
Requirement already satisfied: typing-extensions>=4.14.1 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2->ydata-profiling) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2->ydata-profiling) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.32.0->ydata-profiling) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.32.0->ydata-profiling) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.32.0->ydata-profiling) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.32.0->ydata-profiling) (2026.5.20)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.12/dist-packages (from statsmodels<1,>=0.13.2->ydata-profiling) (1.0.2)
Requirement already satisfied: attrs>=19.3.0 in /usr/local/lib/python3.12/dist-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (26.1.0)
Requirement already satisfied: networkx>=2.4 in /usr/local/lib/python3.12/dist-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (3.6.1)
Collecting puremagic (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling)
  Downloading puremagic-2.2.0-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib<=3.10,>=3.5->ydata-profiling) (1.17.0)
Downloading ydata_profiling-4.18.4-py2.py3-none-any.whl (400 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 400.8/400.8 kB 9.4 MB/s eta 0:00:00
Downloading ImageHash-4.3.2-py2.py3-none-any.whl (296 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 296.7/296.7 kB 25.2 MB/s eta 0:00:00
Downloading dacite-1.9.2-py3-none-any.whl (16 kB)
Downloading filetype-1.2.0-py2.py3-none-any.whl (19 kB)
Downloading minify_html-0.18.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 68.3 MB/s eta 0:00:00
Downloading multimethod-1.12-py3-none-any.whl (10 kB)
Downloading phik-0.12.5-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (679 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 679.7/679.7 kB 44.4 MB/s eta 0:00:00
Downloading visions-0.8.1-py3-none-any.whl (105 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 105.4/105.4 kB 9.5 MB/s eta 0:00:00
Downloading puremagic-2.2.0-py3-none-any.whl (71 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.0/72.0 kB 6.1 MB/s eta 0:00:00
Installing collected packages: minify-html, filetype, puremagic, multimethod, dacite, imagehash, visions, phik, ydata-profiling
Successfully installed dacite-1.9.2 filetype-1.2.0 imagehash-4.3.2 minify-html-0.18.1 multimethod-1.12 phik-0.12.5 puremagic-2.2.0 visions-0.8.1 ydata-profiling-4.18.4

In [26]:
from ydata_profiling import ProfileReport

profile = ProfileReport(
    merged_df,
    title="Credit Risk Report",
    explorative=True
)

profile.to_file("credit_report.html")

print("Report Generated Successfully!")

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/43 [00:00<?, ?it/s]
 16%|█▋        | 7/43 [00:00<00:00, 62.84it/s]
 33%|███▎      | 14/43 [00:00<00:00, 65.71it/s]
 49%|████▉     | 21/43 [00:00<00:00, 66.94it/s]
 65%|██████▌   | 28/43 [00:00<00:00, 45.03it/s]
100%|██████████| 43/43 [00:00<00:00, 57.68it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

Report Generated Successfully!

In [27]:
merged_df.isnull().sum()

customer_id               0
age_csv                   0
gender_csv                0
region_csv                0
education_level_csv       0
employment_type_csv       0
annual_income_csv         0
loan_amount_csv           0
loan_purpose_csv          0
credit_score_csv          0
repayment_history_csv     0
transaction_count_csv     0
spending_ratio_csv        0
join_date_csv             0
default_flag_csv          0
age_json                  0
gender_json               0
region_json               0
education_level_json      0
employment_type_json      0
annual_income_json        0
loan_amount_json          0
loan_purpose_json         0
credit_score_json         0
repayment_history_json    0
transaction_count_json    0
spending_ratio_json       0
join_date_json            0
default_flag_json         0
age                       0
gender                    0
region                    0
education_level           0
employment_type           0
annual_income             0
loan_amount               0
loan_purpose              0
credit_score              0
repayment_history         0
transaction_count         0
spending_ratio            0
join_date                 0
default_flag              0
dtype: int64

In [28]:
from sklearn.impute import SimpleImputer

mean_imp = SimpleImputer(strategy="mean")

merged_df["age"] = mean_imp.fit_transform(
    merged_df[["age"]]
)

In [29]:
from pyspark.sql.merge import MergeIntoWriter
merged_df["age"].isnull().sum()

np.int64(0)

In [30]:
median_imp = SimpleImputer(
    strategy="median"
)

merged_df["annual_income"] = (
    median_imp.fit_transform(
        merged_df[["annual_income"]]
    )
)

In [31]:
merged_df["annual_income"].isnull().sum()

np.int64(0)

In [32]:
cat_imp = SimpleImputer(
    strategy="most_frequent"
)

merged_df["employment_type"] = (
    cat_imp.fit_transform(
        merged_df[["employment_type"]]
    ).ravel()
)

In [33]:
merged_df["employment_type"].isnull().sum()

np.int64(0)

In [34]:
merged_df["income_missing"] = (merged_df["annual_income"].isnull().astype(int))

In [35]:
merged_df["income_missing"].value_counts()

income_missing
0    1000
Name: count, dtype: int64

In [36]:
random_sample = merged_df["annual_income"].dropna()
merged_df.loc[merged_df["annual_income"].isnull(), "annual_income"] = \
    np.random.choice(random_sample, merged_df["annual_income"].isnull().sum())

In [37]:
random_sample = merged_df["annual_income"].dropna()
merged_df.loc[merged_df["annual_income"].isnull(),"annual_income"] = np.random.choice(random_sample, merged_df["annual_income"].isnull().sum())

In [38]:
from sklearn.impute import KNNImputer

knn = KNNImputer(
    n_neighbors=5
)

cols = [
    "annual_income",
    "loan_amount",
    "credit_score"
]

merged_df[cols] = (
    knn.fit_transform(
        merged_df[cols]
    )
)

In [39]:
from sklearn.experimental import (
    enable_iterative_imputer
)

from sklearn.impute import (
    IterativeImputer
)

mice = IterativeImputer()

merged_df[cols] = (
    mice.fit_transform(
        merged_df[cols]
    )
)

In [40]:
cca_df = merged_df.dropna()

In [41]:
from scipy.stats import zscore

z_scores = np.abs(
    zscore(
        merged_df[
            [
                "annual_income",
                "loan_amount",
                "credit_score"
            ]
        ]
    )
)

outliers = (
    z_scores > 3
).any(axis=1)

merged_df_z = merged_df[
    ~outliers
]

In [42]:
Q1 = merged_df[
    "annual_income"
].quantile(0.25)

Q3 = merged_df[
    "annual_income"
].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5*IQR
upper = Q3 + 1.5*IQR

merged_df_iqr = merged_df[
    (
        merged_df["annual_income"]
        >= lower
    )
    &
    (
        merged_df["annual_income"]
        <= upper
    )
]

In [43]:
low = merged_df[
    "annual_income"
].quantile(0.01)

high = merged_df[
    "annual_income"
].quantile(0.99)

merged_df["annual_income"] = (
    merged_df[
        "annual_income"
    ].clip(low,high)
)

In [44]:
from scipy.stats.mstats import winsorize

merged_df[
    "annual_income"
] = winsorize(
    merged_df["annual_income"],
    limits=[0.01,0.01]
)

In [45]:
merged_df.dtypes

customer_id                 int64
age_csv                     int64
gender_csv                 object
region_csv                 object
education_level_csv        object
employment_type_csv        object
annual_income_csv           int64
loan_amount_csv             int64
loan_purpose_csv           object
credit_score_csv            int64
repayment_history_csv       int64
transaction_count_csv       int64
spending_ratio_csv        float64
join_date_csv              object
default_flag_csv            int64
age_json                    int64
gender_json                object
region_json                object
education_level_json       object
employment_type_json       object
annual_income_json          int64
loan_amount_json            int64
loan_purpose_json          object
credit_score_json           int64
repayment_history_json      int64
transaction_count_json      int64
spending_ratio_json       float64
join_date_json             object
default_flag_json           int64
age                       float64
gender                     object
region                     object
education_level            object
employment_type            object
annual_income             float64
loan_amount               float64
loan_purpose               object
credit_score              float64
repayment_history           int64
transaction_count           int64
spending_ratio            float64
join_date                  object
default_flag                int64
income_missing              int64
dtype: object

In [46]:
merged_df["join_date"] = pd.to_datetime(
    merged_df["join_date"]
)

merged_df["year"] = (
    merged_df["join_date"]
    .dt.year
)

merged_df["month"] = (
    merged_df["join_date"]
    .dt.month
)

merged_df["day"] = (
    merged_df["join_date"]
    .dt.day
)

merged_df["weekday"] = (
    merged_df["join_date"]
    .dt.day_name()
)

In [47]:
education_map = {
"Primary":1,
"Secondary":2,
"Graduate":3,
"Post-Graduate":4
}

merged_df[
    "education_level"
] = (
    merged_df[
        "education_level"
    ].map(education_map)
)

In [48]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

merged_df["gender"] = (
    le.fit_transform(
        merged_df["gender"]
    )
)

In [49]:
merged_df = pd.get_dummies(
    merged_df,
    columns=[
        "region",
        "loan_purpose"
    ]
)

In [50]:
merged_df[
    "income_group"
] = pd.cut(
    merged_df["annual_income"],
    bins=4,
    labels=[
        "Low",
        "Medium",
        "High",
        "Very High"
    ]
)

In [51]:
merged_df[
    "income_group"
] = pd.cut(
    merged_df["annual_income"],
    bins=4,
    labels=[
        "Low",
        "Medium",
        "High",
        "Very High"
    ]
)

In [52]:
merged_df[
    "transaction_quantile"
] = pd.qcut(
    merged_df[
        "transaction_count"
    ],
    q=4,
    labels=False
)

In [53]:
from sklearn.cluster import KMeans

kmeans = KMeans(
    n_clusters=4,
    random_state=42
)

merged_df[
    "transaction_cluster"
] = (
    kmeans.fit_predict(
        merged_df[
            ["transaction_count"]
        ]
    )
)

In [54]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

merged_df[
[
"annual_income",
"loan_amount"
]
] = scaler.fit_transform(
merged_df[
[
"annual_income",
"loan_amount"
]
]
)

In [55]:
from sklearn.preprocessing import MinMaxScaler

mm = MinMaxScaler()

merged_df[
[
"credit_score"
]
] = mm.fit_transform(
merged_df[
[
"credit_score"
]
]
)

In [56]:
from sklearn.preprocessing import MaxAbsScaler

ma = MaxAbsScaler()

merged_df[
[
"transaction_count"
]
] = ma.fit_transform(
merged_df[
[
"transaction_count"
]
]
)

In [57]:
from sklearn.preprocessing import RobustScaler

rb = RobustScaler()

merged_df[
[
"repayment_history"
]
] = rb.fit_transform(
merged_df[
[
"repayment_history"
]
]
)

In [58]:
merged_df[
"log_spending"
] = np.log1p(
merged_df[
"spending_ratio"
]
)

In [59]:
merged_df[
"reciprocal_spending"
] = 1/(
merged_df[
"spending_ratio"
]+1
)

In [60]:
merged_df[
"sqrt_spending"
] = np.sqrt(
merged_df[
"spending_ratio"
]
)

In [61]:
from sklearn.preprocessing import PowerTransformer

bc = PowerTransformer(
    method="yeo-johnson"
)

merged_df[
    [
        "annual_income"
    ]
] = bc.fit_transform(
    merged_df[
        [
            "annual_income"
        ]
    ]
)

In [62]:
yj = PowerTransformer(
method="yeo-johnson"
)

merged_df[["loan_amount"]] = yj.fit_transform(
merged_df[["loan_amount"]])

In [63]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

preprocessor = ColumnTransformer(["cat",OneHotEncoder(),["loan_purpose"],("num",StandardScaler(),["annual_income","loan_amount"])])

In [64]:
merged_df["debt_income_ratio"] = (merged_df["loan_amount"]/merged_df["annual_income"])

In [65]:
merged_df["avg_monthly_transactions"] = (merged_df["transaction_count"]/6)

In [66]:
merged_df["spending_income_ratio"] = (merged_df["spending_ratio"]*merged_df["annual_income"])

In [67]:
merged_df.to_csv("final_cleaned_dataset.csv",index=False)

In [68]:
merged_df.head()

,customer_id,age_csv,gender_csv,region_csv,education_level_csv,employment_type_csv,annual_income_csv,loan_amount_csv,loan_purpose_csv,credit_score_csv,...,loan_purpose_Other,income_group,transaction_quantile,transaction_cluster,log_spending,reciprocal_spending,sqrt_spending,debt_income_ratio,avg_monthly_transactions,spending_income_ratio
0,10001,59,Female,South,Primary,Self-Employed,1538977,1436826,Car,385,...,False,High,0,3,2.822569,0.059453,3.977436,5.322002,0.028724,4.625245
1,10002,49,Male,West,Primary,Salaried,386371,1409385,Education,766,...,False,Low,2,2,3.287282,0.037355,5.076416,-1.072266,0.099198,-35.827464
2,10003,35,Female,East,Primary,Self-Employed,796275,1441730,Education,352,...,False,Medium,0,3,3.626206,0.026617,6.047313,-1.960113,0.018704,-29.247506
3,10004,63,Female,North,Primary,Salaried,1874502,274737,Car,534,...,False,High,0,3,4.306764,0.013477,8.555700,-1.505481,0.039746,58.381898
4,10005,28,Male,North,Primary,Salaried,274591,944235,Car,732,...,False,Low,1,0,4.067658,0.017117,7.577599,-0.248872,0.069806,-89.016343

# PART - A

# What is Data Analysis?

**Data Analysis** is the process of collecting, cleaning, transforming, and interpreting data to discover useful information, identify patterns, and support decision-making.

The main goal of data analysis is to convert raw data into meaningful insights.

## Steps of Data Analysis

1. Data Collection
2. Data Cleaning
3. Data Transformation
4. Data Exploration
5. Data Visualization
6. Interpretation and Decision Making

## Importance of Data Analysis

- Improves decision making
- Identifies trends and patterns
- Helps in prediction and forecasting
- Supports business growth

---

# How to Plan a Data Science Project?

A Data Science project should follow a structured approach.

## 1. Business Understanding

Define the problem and project objectives.

**Example:**  
Predict whether a customer will default on a loan.

## 2. Data Collection

Gather data from different sources such as:

- CSV files
- Databases
- APIs
- JSON files

## 3. Data Understanding

Analyze:

- Data types
- Missing values
- Outliers
- Data distribution

## 4. Data Preprocessing

- Handle missing values
- Remove outliers
- Encode categorical variables
- Scale features

## 5. Feature Engineering

Create useful features from existing data.

## 6. Model Building

Train Machine Learning models.

## 7. Evaluation

Measure model performance using metrics.

## 8. Deployment

Deploy the model for real-world use.

---

# How to Frame a Machine Learning Problem?

Framing a Machine Learning problem means converting a business problem into a machine learning task.

## Step 1: Define Objective

**Example:**  
Predict loan default.

## Step 2: Identify Target Variable

**Target:** `default_flag`

- 0 = No Default
- 1 = Default

## Step 3: Identify Features

### Input Variables

- age
- gender
- annual_income
- loan_amount
- credit_score
- repayment_history
- transaction_count
- spending_ratio

## Step 4: Select ML Type

Since the target variable has:

- 0 or 1

It is a:

**Binary Classification Problem**

## Step 5: Define Evaluation Metrics

- Accuracy
- Precision
- Recall
- F1 Score

---

# Explain Tensors with NumPy Examples

## Definition

A **Tensor** is a mathematical structure used to represent data in multiple dimensions.

A tensor can be:

| Tensor Type | Example |
|------------|----------|
| Scalar | Single Number |
| Vector | 1D Array |
| Matrix | 2D Array |
| Higher Order Tensor | 3D+ Array |

---

## 0-D Tensor (Scalar)

```python
import numpy as np

scalar = np.array(10)

print(scalar)
print(scalar.ndim)
```

### Output

```python
10
0
```

---

## 1-D Tensor (Vector)

```python
vector = np.array([10, 20, 30, 40])

print(vector)
print(vector.ndim)
```

### Output

```python
[10 20 30 40]
1
```

---

## 2-D Tensor (Matrix)

```python
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(matrix)
print(matrix.ndim)
```

### Output

```python
[[1 2 3]
 [4 5 6]]

2
```

---

## 3-D Tensor

```python
tensor3d = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

print(tensor3d.ndim)
```

### Output

```python
3
```

---

# Why Tensors are Important?

- Used in Deep Learning
- Store multi-dimensional data
- Efficient mathematical operations
- Used by TensorFlow and PyTorch